on: [pull_request]
name: test
jobs:
  short:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.25.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Short test
      run: go test -short .

  full:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.25.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -parallel 10 .
